# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU)
ps_ip: 127.0.0.1

# ip address of each worker:# of gpus on this worker
# Note that if we collocate ps and worker, then we need to decrease this number of gpus by 1
# E.g., master node has 4 GPUs, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 127.0.0.1:[0,6,0,0,0,0,0,0] # worker_ip: [(# processes on gpu) for gpu in available_gpus]
    #- 10.0.0.4:[5]
    #- 10.0.0.5:[5]
    #- 10.0.0.6:[5]
    #- 10.0.0.7:[5]
    #- 10.0.0.8:[5]
    #- 10.0.0.9:[4]
    #- 10.0.0.10:[4]
    #- 10.0.0.11:[4]
    #- 10.0.0.12:[4]
    #- 10.0.0.13:[4]

exp_path: $HOME/FedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: "zjiangaj"
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source $HOME/anaconda3/bin/activate fedscale    
    - export NCCL_SOCKET_IFNAME='enp129s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs
    - export OPENBLAS_NUM_THREADS=2

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/FedScale/core/evals # Path of log files
    - job_name: google_speech_random_none_all_test                   # Generate logs under this folder: log_path/job_name/time_stamp
    - task: speech
    - total_worker: 50                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: google_speech                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: $HOME/FedScale/dataset/data/google_speech    # Path of the dataset
    - data_map_file: $HOME/FedScale/dataset/data/google_speech/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: $HOME/FedScale/dataset/data/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: $HOME/FedScale/dataset/data/device_info/client_behave_trace
    - model: resnet34                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - gradient_policy: fed-avg                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 20                     # How many rounds to run a testing on the testing set
    - epochs: 501                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 21                       # Remove clients w/ less than 21 samples
    - num_loaders: 4
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 4
    - learning_rate: 0.05
    - batch_size: 20
    - test_bsz: 20
    - sample_mode: random
    - test_mode: all # "default" or "all"


